import React from 'react';

const loading = () => {
    return (
        <div>
           Loading.....
           Loading.....
           Loading.....
           Loading.....
           Loading.....
           Loading.....
           Loading.....
           Loading.....
        </div>
    );
};

export default loading;